// React_Full_Project/src/views/Pages/Register/Register.js
import React, {Component} from "react";
import {Container, Row, Col, Card, CardBlock, CardFooter, Button, Input, InputGroup, InputGroupAddon} from "reactstrap";

class Register extends Component {
    render() {
        return (
            <div className="app flex-row align-items-center">
                <Container>
                    <Row className="justify-content-center">
                        <Col md="6">
                            <Card className="mx-4">
                                <CardBlock className="card-body p-4">
                                    <h1>Register</h1>
                                    <p className="text-muted">Create your account</p>
                                    <InputGroup className="mb-3">
                                        <InputGroupAddon><i className="icon-user"></i>
                                        </InputGroupAddon>
                                        <Input type="text" placeholder="Username" />
                                    </InputGroup>
                                    <InputGroup className="mb-3">
                                        <InputGroupAddon>@</InputGroupAddon>
                                        <Input type="text" placeholder="Email" />
                                    </InputGroup>
                                    <InputGroup className="mb-3">
                                        <InputGroupAddon><i className="icon-lock"></i>
                                        </InputGroupAddon>
                                        <Input type="password" placeholder="Password" />
                                    </InputGroup>
                                    <InputGroup className="mb-4">
                                        <InputGroupAddon><i className="icon-lock"></i>
                                        </InputGroupAddon>
                                        <Input type="password" placeholder="Repeat password" />
                                    </InputGroup>
                                    <Button color="success" block>Create Account</Button>
                                </CardBlock>
                                <CardFooter className="p-4">
                                    <Row>
                                        <Col xs="12" sm="6">
                                            <Button className="btn-facebook" block><span>facebook</span>
                                            </Button>
                                        </Col>
                                        <Col xs="12" sm="6">
                                            <Button className="btn-twitter" block><span>twitter</span>
                                            </Button>
                                        </Col>
                                    </Row>
                                </CardFooter>
                            </Card>
                        </Col>
                    </Row>
                </Container>
            </div>
        );
    }
}

export default Register;

// Vue_Full_Project/src/views/pages/Register.vue
<template>
    <div class="app flex-row align-items-center">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card mx-4">
                        <div class="card-body p-4">
                            <h1>Register</h1>
                            <p class="text-muted">Create your account</p>
                            <div class="input-group mb-3">
                                <span class="input-group-addon"><i class="icon-user"></i></span>
                                <input type="text" class="form-control" placeholder="Username">
                            </div>

                            <div class="input-group mb-3">
                                <span class="input-group-addon">@</span>
                                <input type="text" class="form-control" placeholder="Email">
                            </div>

                            <div class="input-group mb-3">
                                <span class="input-group-addon"><i class="icon-lock"></i></span>
                                <input type="password" class="form-control" placeholder="Password">
                            </div>

                            <div class="input-group mb-4">
                                <span class="input-group-addon"><i class="icon-lock"></i></span>
                                <input type="password" class="form-control" placeholder="Repeat password">
                            </div>

                            <button type="button" class="btn btn-block btn-success">Create Account</button>
                        </div>
                        <div class="card-footer p-4">
                            <div class="row">
                                <div class="col-6">
                                    <button class="btn btn-block btn-facebook" type="button"><span>facebook</span>
                                    </button>
                                </div>
                                <div class="col-6">
                                    <button class="btn btn-block btn-twitter" type="button"><span>twitter</span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: 'Register'
    }
</script>
