// Angular2_CLI_Full_Project/src/app/components/cards.component.ts
import {Component} from '@angular/core';

@Component({
    templateUrl: 'cards.component.html'
})
export class CardsComponent {

    constructor() {}

}

<div class="animated fadeIn">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="card">
                <div class="card-header">
                    Card title
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card">
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
                <div class="card-footer">Card footer</div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-check"></i>Card with icon
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card">
                <div class="card-header">
                    Card with switch
                    <label class="switch switch-sm switch-text switch-info float-right mb-0">
                        <input type="checkbox" class="switch-input">
                        <span class="switch-label" data-on="On" data-off="Off"></span>
                        <span class="switch-handle"></span>
                    </label>
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card">
                <div class="card-header">
                    Card with label
                    <span class="badge badge-success float-right">Success</span>
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card">
                <div class="card-header">
                    Card with label
                    <span class="badge badge-pill badge-danger float-right">42</span>
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
    </div><!--/.row-->
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="card card-outline-primary">
                <div class="card-header">
                    Card outline
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-outline-secondary">
                <div class="card-header">
                    Card outline
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-outline-success">
                <div class="card-header">
                    Card outline
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-outline-info">
                <div class="card-header">
                    Card outline
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-outline-warning">
                <div class="card-header">
                    Card outline
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-outline-danger">
                <div class="card-header">
                    Card outline
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
    </div><!--/.row-->

    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="card card-accent-primary">
                <div class="card-header">
                    Card with accent
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-accent-secondary">
                <div class="card-header">
                    Card with accent
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-accent-success">
                <div class="card-header">
                    Card with accent
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-accent-info">
                <div class="card-header">
                    Card with accent
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-accent-warning">
                <div class="card-header">
                    Card with accent
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-accent-danger">
                <div class="card-header">
                    Card with accent
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
    </div><!--/.row-->
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-primary text-center">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-success text-center">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-info text-center">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-warning text-center">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-danger text-center">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-primary text-center">
                <div class="card-block">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </div>
            </div>
        </div><!--/.col-->
    </div><!--/.row-->
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-primary">
                <div class="card-header">
                    Card title
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-success">
                <div class="card-header">
                    Card title
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-info">
                <div class="card-header">
                    Card title
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-warning">
                <div class="card-header">
                    Card title
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
        <div class="col-sm-6 col-md-4">
            <div class="card card-inverse card-danger">
                <div class="card-header">
                    Card title
                </div>
                <div class="card-block">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </div>
            </div>
        </div><!--/.col-->
    </div><!--/.row-->
</div>

// Vue_Full_Project/src/views/components/Cards.vue
<template>
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <b-card header="Card title">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card show-footer>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                    <div slot="footer">Card footer</div>
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="<i class='fa fa-check'></i> Card with icon">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card>
                    <div slot="header">
                        Card with switch
                        <label class="switch switch-sm switch-text switch-info float-right mb-0">
                            <input type="checkbox" class="switch-input">
                            <span class="switch-label" data-on="On" data-off="Off"></span>
                            <span class="switch-handle"></span>
                        </label>
                    </div>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card>
                    <div slot="header">
                        Card with label
                        <span class="badge badge-success float-right">Success</span>
                    </div>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card>
                    <div slot="header">
                        Card with label
                        <span class="badge badge-pill badge-danger float-right">42</span>
                    </div>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
        </div>
        <!--/.row-->
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <b-card header="Card outline" class="border-primary">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card outline" class="border-secondary">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card outline" class="border-success">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card outline" class="border-info">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card outline" class="border-warning">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card outline" class="border-danger">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
        </div>
        <!--/.row-->

        <div class="row">
            <div class="col-sm-6 col-md-4">
                <b-card variant="accent-primary" header="Card with accent">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card variant="accent-secondary" header="Card with accent">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card variant="accent-success" header="Card with accent">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card variant="accent-info" header="Card with accent">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card variant="accent-warning" header="Card with accent">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card variant="accent-danger" header="Card with accent">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
        </div>
        <!--/.row-->
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <b-card class="bg-primary text-center">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card class="bg-success text-center">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card class="bg-info text-center">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card class="bg-warning text-center">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card class="bg-danger text-center">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card class="bg-secondary text-center">
                    <blockquote class="card-blockquote">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                        <footer>Someone famous in
                            <cite title="Source Title">Source Title</cite>
                        </footer>
                    </blockquote>
                </b-card>
            </div>
            <!--/.col-->
        </div>
        <!--/.row-->
        <div class="row">
            <div class="col-sm-6 col-md-4">
                <b-card header="Card title" class="bg-primary">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card title" class="bg-success">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card title" class="bg-info">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card title" class="bg-warning">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card title" class="bg-danger">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
            <div class="col-sm-6 col-md-4">
                <b-card header="Card title" class="bg-secondary">
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
                </b-card>
            </div>
            <!--/.col-->
        </div>
        <!--/.row-->
    </div>
</template>

<script>
    export default {
        name: 'cards'
    }
</script>
